#!/usr/bin/env bash
# script displays the time for 12 hours and 59 minutes:
# displays hours from 0 to 12
# displays minutes from 1 to 59
# using while loop

i=0
while ((i < 13))
do
	echo "Hour: $i"
	j=1
	while ((j < 60))
	do
		echo "$j"
		((j++))
	done
	((i++))
done
